### ISSUE TITLE
How can I trace packet after forwarding with XDP?

### ISSUE THREAD

**Issue by 2cfg** [xdp-project/xdp-tutorial#220]
I have one network interface in my system with many VLAN. And I use static routes between them.
```
    enp3s0f1:
      addresses: [192.168.170.6/24]
      routes:
        - to: 1.1.1.0/24
          via: 192.168.170.6

  vlans:
    vlan302:
      id: 302
      link: enp3s0f1
      addresses: [ "10.0.30.2/32" ]
      routes:
      - to: 2.2.2.0/24
        via: 10.0.30.2

    vlan304:
      id: 304
      link: enp3s0f1
      addresses: [ "10.0.30.4/32" ]
      routes:
      - to: 3.3.3.0/24
        via: 10.0.30.4
```

When I use netsniff-ng (tcpdump) on interface enp3s0f1, I see incoming and outgoing packets with VLAN tags corresponding to the incoming and outgoing interface.

But, when I use XDP program on inteface enp3s0f1, I see only one packet with VLAN tag corresponding to the incoming interface (before forwarding). How can I trace packet in my XDP-program after forwarding by Linux network stack?

For testing I plugged in a second network interface  and configured it for outgoing traffic. In this case, I run a separate XDP-program on each network interface and process the incoming and outgoing packets. It doesn't work with one interface.
