### ISSUE TITLE
Trying to write XDP for redirecting packets in veth inside kubernetes

### ISSUE THREAD

**Issue by vincent5753** [xdp-project/xdp-tutorial#399]
Hi, I am newbie to XDP.
I got inspired by this tutorial and wanted to test redirecting packets between veths on kubernetes

I used hard-coded IP and MAC address in the XDP, and used return `bpf_redirect`、`XDP_TX`、`XDP_REDIRECT`
but none of them worked.

I traced XDP using perf, and here is the result
```
➜  ebpf sudo perf trace --event 'xdp:*'
# bpf_redirect(ifindex2, 0)
     0.000 ping/936614 xdp:xdp_redirect_err:prog_id=1426 action=REDIRECT ifindex=66 to_ifindex=67 err=-6
# XDP_TX
 15562.756 ping/936800 xdp:xdp_bulk_tx:ifindex=66 action=TX sent=0 drops=1 err=-6
# XDP_REDIRECT
 27807.646 ping/936940 xdp:xdp_redirect_err:prog_id=1428 action=REDIRECT ifindex=66 to_ifindex=0 err=-22
```

My ENV setup is in fowlling
```
OS: Ubuntu 20.04(VM on Proxmox VE)
Kernel: 5.4.0-144-generic
Kubernetes: 1.23.17
CNI: flannel
clang: Ubuntu clang version 11.0.0-2~ubuntu20.04.1
```

test Pod YAML
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ping-1-privileged
spec:
  containers:
  - name: ping-1-privileged
    image: ubuntu20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: ping-2-privileged
spec:
  containers:
  - name: ping-2-privileged
    image: ubuntu20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: ping-3-privileged
spec:
  containers:
  - name: ping-3-privileged
    image: ubuntu20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
```

Can anyone point out what I was wrong or missing?
